# Generated by Django 5.2.4 on 2026-02-26 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_remove_product_is_favorite_alter_product_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión de pago o carrito anónimo', max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia de la pasarela de pagos', max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado'), ('FAILED', 'Pago Fallido'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Dirección de envío')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra (Unidad)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariant', verbose_name='Variante de Producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
