# Generated by Django 5.2.4 on 2026-03-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre de contacto'),
        ),
    ]
