# Generated by Django 5.2.4 on 2026-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de envío'),
        ),
    ]
