# Generated by Django 5.2.4 on 2026-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Imagen')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('button_text', models.CharField(default='Comprar Ahora', max_length=50, verbose_name='Texto Botón')),
                ('button_link', models.CharField(default='/productos', max_length=255, verbose_name='Link Botón')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Slide de Hero',
                'verbose_name_plural': 'Slides de Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción Corta')),
                ('long_description', models.TextField(verbose_name='Descripción Larga')),
                ('cta_text', models.CharField(max_length=100, verbose_name='Texto CTA')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Sección Sobre Nosotros',
                'verbose_name_plural': 'Sección Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('cta_text', models.CharField(max_length=100, verbose_name='Texto Botón')),
                ('cta_link', models.CharField(default='/#footer', max_length=255, verbose_name='Link Botón')),
                ('background_image', models.ImageField(upload_to='cta/', verbose_name='Imagen de Fondo')),
            ],
            options={
                'verbose_name': 'Banner CTA',
                'verbose_name_plural': 'Banner CTA',
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('Coffee', 'Café'), ('Award', 'Premio'), ('Leaf', 'Hoja'), ('Truck', 'Camión'), ('Heart', 'Corazón')], default='Coffee', max_length=50, verbose_name='Icono')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Característica (Feature)',
                'verbose_name_plural': 'Características (Features)',
                'ordering': ['order'],
            },
        ),
    ]
