# Generated by Django 5.2.4 on 2026-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='button_text_en',
            field=models.CharField(default='Buy Now', max_length=50, verbose_name='Texto Botón (EN)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.TextField(blank=True, verbose_name='Subtítulo (EN)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto CTA (EN)'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Corta (EN)'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='long_description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Larga (EN)'),
        ),
        migrations.AddField(
            model_name='homeabout',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='homecta',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto Botón (EN)'),
        ),
        migrations.AddField(
            model_name='homecta',
            name='subtitle_en',
            field=models.TextField(blank=True, verbose_name='Subtítulo (EN)'),
        ),
        migrations.AddField(
            model_name='homecta',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='homefeature',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción (EN)'),
        ),
        migrations.AddField(
            model_name='homefeature',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (EN)'),
        ),
    ]
