# Generated by Django 5.2.4 on 2026-02-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_heroslide_button_text_en_heroslide_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['order'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='homeabout',
            options={'verbose_name': 'Sobre Nosotros', 'verbose_name_plural': 'Sobre Nosotros'},
        ),
        migrations.AlterModelOptions(
            name='homecta',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='homefeature',
            options={'ordering': ['order'], 'verbose_name': 'Características', 'verbose_name_plural': 'Características'},
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.CharField(default='/productos', help_text='URL o ruta a la que redirigirá el botón (ej: /productos).', max_length=255, verbose_name='Enlace del Botón'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(default='Comprar Ahora', help_text='El texto que aparecerá dentro del botón.', max_length=50, verbose_name='Texto del Botón (Español)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text_en',
            field=models.CharField(default='Buy Now', help_text='Texto del botón en inglés.', max_length=50, verbose_name='Texto del Botón (Inglés)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(help_text='Imagen que se mostrará en el carrusel principal. Tamaño recomendado: 1920x1080px.', upload_to='hero/', verbose_name='Imagen de Fondo'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está marcado, esta diapositiva será visible en la página.', verbose_name='¿Está Activo?'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Número para determinar la posición en el carrusel (menor número aparece primero).', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.TextField(help_text='Texto secundario que aparece debajo del título.', verbose_name='Subtítulo (Español)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.TextField(blank=True, help_text='Texto secundario en inglés.', verbose_name='Subtítulo (Inglés)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(help_text='Título principal de la diapositiva en español.', max_length=200, verbose_name='Título (Español)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, help_text='Título principal en inglés.', max_length=200, verbose_name='Título (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='cta_text',
            field=models.CharField(help_text='Texto del botón o enlace para saber más.', max_length=100, verbose_name='Texto de Llamado a la Acción (Español)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto de Llamado a la Acción (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='description',
            field=models.TextField(help_text='Breve introducción que se muestra debajo del título.', verbose_name='Descripción Corta (Español)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Corta (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen representativa para la sección.', null=True, upload_to='about/', verbose_name='Imagen de la Sección'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='long_description',
            field=models.TextField(help_text='Contenido detallado sobre la historia o misión de la cafetería.', verbose_name='Descripción Larga (Español)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='long_description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Larga (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='title',
            field=models.CharField(help_text="Título que encabeza la sección 'Sobre Nosotros'.", max_length=200, verbose_name='Título de la Sección (Español)'),
        ),
        migrations.AlterField(
            model_name='homeabout',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título de la Sección (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='background_image',
            field=models.ImageField(help_text='Imagen que se mostrará detrás de los textos del banner.', upload_to='cta/', verbose_name='Imagen de Fondo'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='cta_link',
            field=models.CharField(default='/productos', help_text='Destino del click en el banner.', max_length=255, verbose_name='Enlace de Acción'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='cta_text',
            field=models.CharField(help_text='Texto que invita a la acción.', max_length=100, verbose_name='Texto del Botón (Español)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto del Botón (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='subtitle',
            field=models.TextField(help_text='Texto de apoyo para el banner.', verbose_name='Subtítulo (Español)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='subtitle_en',
            field=models.TextField(blank=True, verbose_name='Subtítulo (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='title',
            field=models.CharField(help_text='Título llamativo que aparece en el banner inferior.', max_length=200, verbose_name='Título del Banner (Español)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título del Banner (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='description',
            field=models.TextField(help_text='Explicación detallada de esta ventaja o característica.', verbose_name='Descripción (Español)'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción (Inglés)'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='icon',
            field=models.CharField(choices=[('Coffee', 'Café'), ('Award', 'Premio'), ('Leaf', 'Hoja'), ('Truck', 'Camión'), ('Heart', 'Corazón')], default='Coffee', help_text='Seleccione el icono que mejor represente esta característica.', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Prioridad de aparición.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='title',
            field=models.CharField(help_text='Nombre corto de la característica.', max_length=100, verbose_name='Título (Español)'),
        ),
        migrations.AlterField(
            model_name='homefeature',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Título (Inglés)'),
        ),
    ]
