# Generated by Django 5.2.4 on 2026-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_heroslide_optional_title_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecta',
            name='subtitle',
            field=models.TextField(blank=True, default='', help_text='Texto de apoyo para el banner.', verbose_name='Subtítulo (Español)'),
        ),
        migrations.AlterField(
            model_name='homecta',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Título llamativo que aparece en el banner inferior.', max_length=200, verbose_name='Título del Banner (Español)'),
        ),
    ]
