# Generated by Django 5.2.4 on 2026-03-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_homecta_subtitle_alter_homecta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefeature',
            name='value',
        ),
    ]
