# Generated by Django 4.2.28 on 2026-02-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo (Ej: Teléfono, Email)')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (FontAwesome)')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'Pregunta Frecuente', 'verbose_name_plural': 'Preguntas Frecuentes'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=160, verbose_name='Pregunta'),
        ),
    ]
