# Generated by Django 5.2.4 on 2026-02-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_es',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
