# Generated by Django 4.2.28 on 2026-02-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content_en_blogpost_content_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt_es',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title_es',
        ),
    ]
