# Generated by Django 5.2.4 on 2026-02-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_content_en_blogpost_excerpt_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['published_at'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Cuerpo principal del artículo.', verbose_name='Contenido Completo (Español)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Contenido Completo (Inglés)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(help_text='Imagen principal que aparecerá en el listado del blog.', upload_to='blog/covers/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Breve descripción que aparece en el listado antes de leer el artículo completo.', max_length=250, verbose_name='Resumen/Extracto (Español)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Resumen/Extracto (Inglés)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Si está marcado, el artículo será visible para todos en la web.', verbose_name='Artículo Publicado'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que el artículo será visible.', null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL del artículo.', unique=True, verbose_name='URL Amigable'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Encabezado principal del artículo del blog.', max_length=160, verbose_name='Título del Artículo (Español)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Título (Inglés)'),
        ),
    ]
