# Generated by Django 5.2.4 on 2026-02-13 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='clients/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='clients/covers/')),
                ('testimonial', models.TextField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clients/gallery/')),
                ('alt', models.CharField(blank=True, max_length=120)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clients.client')),
            ],
            options={
                'verbose_name': 'imagen de cliente',
                'verbose_name_plural': 'imagenes de clientes',
            },
        ),
    ]
