# Generated by Django 5.2.4 on 2026-02-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location_es',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='name_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='testimonial_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='testimonial_es',
            field=models.TextField(null=True),
        ),
    ]
