# Generated by Django 4.2.28 on 2026-02-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_location_en_client_location_es_client_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='client',
            name='location_es',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='client',
            name='testimonial_en',
        ),
        migrations.RemoveField(
            model_name='client',
            name='testimonial_es',
        ),
    ]
