# Generated by Django 5.2.4 on 2026-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_location_en_remove_client_location_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='testimonial_en',
            field=models.TextField(blank=True),
        ),
    ]
