# Generated by Django 5.2.4 on 2026-02-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_testimonial_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created_at'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientimage',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'Galería'},
        ),
        migrations.AlterField(
            model_name='client',
            name='cover',
            field=models.ImageField(blank=True, help_text='Imagen opcional para destacar este cliente.', null=True, upload_to='clients/covers/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está marcado, este cliente aparecerá en la web.', verbose_name='Cliente Visible'),
        ),
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Coordenada de latitud para el mapa.', max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, help_text='Ciudad o zona del cliente.', max_length=120, verbose_name='Ubicación/Ciudad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo del cliente o empresa.', upload_to='clients/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Coordenada de longitud para el mapa.', max_digits=18, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Cliente/Empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente. Identificador único para la URL.', unique=True, verbose_name='URL Amigable'),
        ),
        migrations.AlterField(
            model_name='client',
            name='testimonial',
            field=models.TextField(help_text='Comentario o reseña del cliente sobre la cafetería.', verbose_name='Testimonio (Español)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='testimonial_en',
            field=models.TextField(blank=True, verbose_name='Testimonio (Inglés)'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='alt',
            field=models.CharField(blank=True, max_length=120, verbose_name='Texto Alternativo'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='image',
            field=models.ImageField(help_text='Foto adicional del cliente o sus proyectos.', upload_to='clients/gallery/', verbose_name='Imagen'),
        ),
    ]
