# Generated by Django 5.2.4 on 2026-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_options_alter_clientimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, help_text="Información detallada que aparece al hacer clic en 'Ver más'.", verbose_name='Descripción Larga (Español)'),
        ),
        migrations.AddField(
            model_name='client',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Larga (Inglés)'),
        ),
    ]
