# Generated by Django 5.2.4 on 2026-03-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_description_client_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Texto Alternativo (Inglés)'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='alt',
            field=models.CharField(blank=True, max_length=120, verbose_name='Texto Alternativo (Español)'),
        ),
    ]
