# Generated by Django 4.2.28 on 2026-02-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('specialty', 'Especialidad'), ('blend', 'Mezcla'), ('decaf', 'Descafeinado'), ('accessories', 'Accesorios')], default='specialty', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc_en',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
