# Generated by Django 4.2.28 on 2026-02-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('specialty', 'Especialidad'), ('blend', 'Mezcla'), ('decaf', 'Descafeinado'), ('accessories', 'Accesorios')], default='specialty', max_length=20),
        ),
    ]
