# Generated by Django 5.2.4 on 2026-02-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'Galería'},
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de unidades disponibles.', verbose_name='Stock / Cantidad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Ej: Cafés, Repostería, etc.', max_length=60, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre (Inglés)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL. Se genera automáticamente si se deja vacío.', unique=True, verbose_name='URL Amigable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, help_text='Imagen principal que aparecerá en el catálogo.', null=True, upload_to='products/cover/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_sheet',
            field=models.FileField(blank=True, help_text='Archivo descargable opcional con especificaciones técnicas.', upload_to='products/datasheets/', verbose_name='Ficha Técnica (PDF)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción Completa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción Completa (Inglés)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se desactiva automáticamente si el stock es 0.', verbose_name='Producto Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre (Inglés)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta actual.', max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, help_text='Pequeña frase descriptiva para listados. Se autogenera de la descripción si se deja vacía.', max_length=160, verbose_name='Descripción Corta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Descripción Corta (Inglés)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para la URL del producto.', unique=True, verbose_name='URL Amigable'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Breve descripción de la imagen para personas con discapacidad visual.', max_length=120, verbose_name='Texto Alternativo (Accesibilidad)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Cargue fotos adicionales para mostrar en la galería del producto.', upload_to='products/gallery/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='Producto'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
