# Generated by Django 5.2.4 on 2026-02-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text="Si está marcado, este producto aparecerá en la sección 'Nuestros Favoritos' del inicio.", verbose_name='Destacar en Inicio'),
        ),
    ]
