# Generated by Django 5.2.4 on 2026-02-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta base o para la variante principal.', max_digits=12, null=True, verbose_name='Precio Base'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(help_text='Ej: 250 gr, 500 gr', max_length=50, verbose_name='Peso/Gramaje')),
                ('grind', models.CharField(help_text='Ej: Molido, En pepa, Cápsulas', max_length=100, verbose_name='Molienda/Presentación')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de esta Variante')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['price'],
            },
        ),
    ]
