# Generated by Django 5.2.4 on 2026-02-27 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_is_favorite_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
