# Generated by Django 5.2.4 on 2026-02-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options_product_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text="Marcar para mostrar este producto en la sección 'Nuestros Favoritos' del inicio.", verbose_name='Producto Favorito'),
        ),
    ]
