# Generated by Django 5.2.4 on 2026-03-03 18:10

from django.db import migrations


def seed_cafe_category(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Category.objects.get_or_create(
        slug='cafe',
        defaults={'name': 'Café', 'name_en': 'Coffee', 'order': 0}
    )


def remove_cafe_category(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    Category.objects.filter(slug='cafe').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_add_is_favorite_to_product'),
    ]

    operations = [
        migrations.RunPython(seed_cafe_category, remove_cafe_category),
    ]
