# Generated by Django 5.2.4 on 2026-03-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_seed_cafe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Texto Alternativo (Inglés)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='grind_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Molienda/Presentación (Inglés)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Peso/Gramaje (Inglés)'),
        ),
    ]
